spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///E:\springBoot\ecommerce\configserver\configserver\src\main\resources\config
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"